import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./reset.css";
import "./globals.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import { Analytics } from '@vercel/analytics/react';

const roboto = Roboto_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "🏏 T20 Visualization",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true} >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
